### ISSUE TITLE
English version of README.md

### ISSUE THREAD

**Issue by iikuzmychov** [Lazuplis-Mei/ClassicalCryptography#1]
Hi, I found your repo really-really cool! Unfortunately, the whole `README.md` file is written in your native language, so it's not so easy to read, even when translating the whole page with Google Translator. I think it can be useful for many people too, so I'm asking you to create a `EN.README.md` or smth like this pleaaase 🙏

**Comment by Lazuplis-Mei** [comment]
OK, I might translate it.

**Comment by Lazuplis-Mei** [comment]
> Hi, I found your repo really-really cool! Unfortunately, the whole `README.md` file is written in your native language, so it's not so easy to read, even when translating the whole page with Google Translator. I think it can be useful for many people too, so I'm asking you to create a `EN.README.md` or smth like this pleaaase 🙏

OK, I might translate it.

**Comment by Lazuplis-Mei** [comment]
Although I tried to translate it, it may still be difficult to read

**Comment by iikuzmychov** [comment]
Thanks a lot! I take a look and the translation seems pretty good!
